### ISSUE TITLE
problem mit lautstärke

### ISSUE THREAD

**Issue by krobipd** [klein0r/ioBroker.lametric#27]
hey vielen dank für deinen tollen adapter

mir ist seit einiger zeit aufgefallen das ich es probleme mit dem setzen der lautstärke gibt
ich habe ein wöchentliches skript das die lautstärke meiner zwei lametrics auf einen gewissen level setzt damit sie immer gleich laut sind.

da ist mir aufgefallen das ich immer eine fehlermeldung bekomme
lautstärke änderungen - manuell bei den datenpunkten - werden auch nicht bestätigt.

folgende fehlermeldung bekomme ich

`(1880) received error 500 response from /api/v2/device/audio with content: {"errors":[{"message":"Audio state error putting settings Unknown error"}]}
--`

**Comment by klein0r** [comment]
Ich konnte das Probleme gerade reproduzieren. Das passiert nur, wenn ich eine Lautstärke setze, welche über Max-Volume liegt (keine Ahnung seit wann es das gibt). Bei mir steht in der App `Sound volume level is limited, because the device is powered from a computer`. Was aber gar nicht stimmt?!

Also ist das Limit bei mir aktuell 69. Wenn ich einen Wert darunter setze, dann geht alles.

https://github.com/lametric/Documentation/issues/17

**Comment by klein0r** [comment]
Das gleiche gilt übrigens auch für die Helligkeit?! Dort kann ich auch nur noch maximal 75 setzen.
